### ISSUE TITLE
Embed not working

### ISSUE THREAD

**Issue by MattMski** [discord-php/DiscordPHP#1035]
**Environment**
- PHP Version:
    - 7.4.33
- DiscordPHP Version:
    - 7.3.3

**Describe the bug**
Hello, for some reason I noticed that all my embed commands on my bot stopped working. Not sure if something is broken but I am unable to send any embeds. I know I didn't change anything

**To Reproduce**
```
1. Create embed
2. Send embed message
```

**Expected behavior**
A embed being displayed on Discord

**Screenshots**

**Additional context**

**Comment by b3r3nd** [comment]
I am having the exact same issue since today, bot works fine just all embeds are broken.. Idk what discord did honestly.

Stack trace from my dev VM:

callback failed: Discord\Http\Exceptions\RequestFailedException: Bad Request - {     "code": 50035,     "errors": {         "data": {             "embeds": {                 "0": {                     "footer": {                         "icon_url": {                             "_errors": [                                 {                                     "code": "URL_TYPE_INVALID_SCHEME",                                     "message": "Scheme \"\" is not supported. Scheme must be one of ('http', 'https')."                                 }                             ]                         }                     }                 }             }         }     },     "message": "Invalid Form Body" } in /home/vagrant/code/discord/vendor/discord-php/http/src/Discord/Http.php:500 Stack trace: #0 /home/vagrant/code/discord/vendor/discord-php/http/src/Discord/Http.php(375): Discord\Http\Http->handleError() #1 /home/vagrant/code/discord/vendor/react/promise/src/FulfilledPromise.php(42): Discord\Http\Http->Discord\Http\{closure}() #2 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done() #3 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}() #4 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle() #5 /home/vagrant/code/discord/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}() #6 /home/vagrant/code/discord/vendor/react/http/src/Io/Transaction.php(89): React\Promise\Deferred->resolve() #7 /home/vagrant/code/discord/vendor/react/promise/src/FulfilledPromise.php(28): React\Http\Io\Transaction->React\Http\Io\{closure}() #8 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then() #9 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}() #10 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle() #11 /home/vagrant/code/discord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}() #12 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done() #13 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}() #14 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle() #15 /home/vagrant/code/discord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}() #16 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done() #17 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}() #18 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle() #19 /home/vagrant/code/discord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}() #20 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done() #21 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}() #22 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle() #23 /home/vagrant/code/discord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}() #24 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done() #25 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}() #26 /home/vagrant/code/discord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle() #27 /home/vagrant/code/discord/vendor/react/promise-stream/src/functions.php(79): React\Promise\Promise::React\Promise\{closure}() #28 /home/vagrant/code/discord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Promise\Stream\{closure}() #29 /home/vagrant/code/discord/vendor/react/http/src/Io/ReadableBodyStream.php(50): Evenement\EventEmitter->emit() #30 /home/vagrant/code/discord/vendor/react/http/src/Io/ReadableBodyStream.php(151): React\Http\Io\ReadableBodyStream->close() #31 /home/vagrant/code/discord/vendor/react/http/src/Io/ReadableBodyStream.php(33): React\Http\Io\ReadableBodyStream->handleEnd() #32 /home/vagrant/code/discord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\ReadableBodyStream->React\Http\Io\{closure}() #33 /home/vagrant/code/discord/vendor/react/http/src/Client/Request.php(163): Evenement\EventEmitter->emit() #34 /home/vagrant/code/discord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Client\Request->handleData() #35 /home/vagrant/code/discord/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #36 /home/vagrant/code/discord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}() #37 /home/vagrant/code/discord/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #38 /home/vagrant/code/discord/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #39 /home/vagrant/code/discord/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #40 /home/vagrant/code/discord/vendor/team-reflex/discord-php/src/Discord/Discord.php(1440): React\EventLoop\StreamSelectLoop->run() #41 /home/vagrant/code/discord/app/Console/Commands/RunBot.php(32): Discord\Discord->run() #42 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\RunBot->handle() #43 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #44 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #45 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #46 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call() #47 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call() #48 /home/vagrant/code/discord/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute() #49 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run() #50 /home/vagrant/code/discord/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run() #51 /home/vagrant/code/discord/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand() #52 /home/vagrant/code/discord/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun() #53 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run() #54 /home/vagrant/code/discord/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run() #55 /home/vagrant/code/discord/artisan(37): Illuminate\Foundation\Console\Kernel->handle() #56 {main} [] []

**Comment by PeanutNL** [comment]
We should also check the URL on the setImage and setThumbnail functions

**Comment by b3r3nd** [comment]
> We should also check the URL on the setImage and setThumbnail functions

Not sure if that matters, at least I do not encounter any issues there but who knows..

**Comment by MattMski** [comment]
> public function setFooter(string $text, string|null $iconurl = null): self
>     {
>         if (poly_strlen($text) === 0) {
>             $this->footer = null;
>         } elseif (poly_strlen($text) > 2048) {
>             throw new \LengthException('Footer text can not be longer than 2048 characters.');
>         } elseif ($this->exceedsOverallLimit(poly_strlen($text))) {
>             throw new \LengthException('Embed text values collectively can not exceed than 6000 characters');
>         } else {
>             $this->footer = [
>                 'text' => $text,
>                 'icon_url' => $iconurl,
>             ];
>         }
> 
>         return $this;
>     }

hey @b3r3nd appreciate the quick response and fix. Glad to see something pushed out soon as well. Temp fix works for now, thank you!

**Comment by MattMski** [comment]
> @MattMski
> 
> Not sure if you are trying to fix it or not. But it must be changed in the DiscordPHP Lib.
> 
> There is a function called setFooter() in de Embed class, this function accepts the second parameter as icon URL. If none is given its sets the value to an empty string, which now is broken because it needs to be set to an actual NULL value. I am not entirely sure what the best solution might be, for me I fixed it now changing the required string type and setting a default NULL value.

hey @b3r3nd appreciate the quick response and fix. Glad to see something pushed out soon as well. 

Getting an error PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE)

is this a PHP 8 only fix?

**Comment by b3r3nd** [comment]
> > @MattMski
> > Not sure if you are trying to fix it or not. But it must be changed in the DiscordPHP Lib.
> > There is a function called setFooter() in de Embed class, this function accepts the second parameter as icon URL. If none is given its sets the value to an empty string, which now is broken because it needs to be set to an actual NULL value. I am not entirely sure what the best solution might be, for me I fixed it now changing the required string type and setting a default NULL value.
> 
> hey @b3r3nd appreciate the quick response and fix. Glad to see something pushed out soon as well.
> 
> Getting an error PHP Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE)
> 
> is this a PHP 8 only fix?
> 
> Edit: fixed by switching string|null to string

Yes it was for php 8.0, but a fix has already been merged so if you pull issue should be resolved.

**Comment by MattMski** [comment]
> Yes it was for php 8.0, but a fix has already been merged so if you pull issue should be resolved.

Worked for me, thanks @b3r3nd
