### ISSUE TITLE
Rate limits are not being respected

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#488]
When a large number of HTTP requests is sent, DiscordPHP does not behave properly and will send all these requests regardless of whether it is time to stop.  I can confirm that this has to do with my TLS handshake failed issue, when adding roles en masse.  DiscordPHP crashes and does not know how to properly handle both kinds of situations. 

When I restarted the bot, a bunch of undefined property errors started showing. I tried to `var_dump()`, confirming the hypothesis.  It was a gloabl rate limit, which was executing broken code.  This limit shouldn't have been hit in the first place.

```
object(stdClass)#100 (2) {
  ["code"]=>
  int(0)
  ["message"]=>
  string(212) "You are being blocked from accessing our API temporarily due to exceeding our rate limits
frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward."
}
```

```
You are being blocked from accessing our API temporarily due to exceeding our rate limits
frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.
```

**Comment by valzargaming** [comment]
![image](https://user-images.githubusercontent.com/7202504/105831648-f9762480-5f94-11eb-93e3-f4603f8052fd.png)

**Comment by key2peace** [comment]
actually, NORMAL global limits are being detected abd handled decently, but this one not, and the error message in there is clear:

string(212) "You are being blocked from accessing our API temporarily due to **exceeding our rate limits
frequently**. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward."

if you look at https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit, you see that the limit you suffer from gets applied when exceeding 10k limit hits / 10 minutes / **IP**. Thats quite a lot... The only ways to prevent these are:
- get more public ipv4's assigned to your hosting enviroment and bind each bot to a different ip (sadly, for the time being,, ipv6 is not an option yet)
- check if yoiu actually need to perform that action
- wrap bulk ccommands around a timer construct that performs the actions in smaller batches, and not all at once

**Comment by kenygamer** [comment]
> actually, NORMAL global limits are being detected and handled decently, but this one not, and the error message in there is clear:
> 
> string(212) "You are being blocked from accessing our API temporarily due to **exceeding our rate limits frequently**. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward."
> 
> if you look at https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit, you see that the limit you suffer from gets applied when exceeding 10k limit hits / 10 minutes / **IP**. Thats quite a lot... The only ways to prevent these are:
> 
> * get more public ipv4's assigned to your hosting enviroment and bind each bot to a different ip (sadly, for the time being,, ipv6 is not an option yet)
> * check if yoiu actually need to perform that action
> * wrap bulk commands around a timer construct that performs the actions in smaller batches, and not all at once

Thanks for the advice. Indeed, DiscordHP needs better handling for when this request limit is hit.

I will do that. It is a dedicated server so I can do that.

**Comment by davidcole1340** [comment]
I'm planning on implementing a global HTTP queue, since at the moment it is only per-endpoint (maybe this will get fixed when I change to use general endpoints rather than exact). 

Bulk member role updates are unfourtunately not a good idea, since the ratelimit is approx. 10/10s per guild (basically 1 role update per second). To ensure no rate limits are broken best way to do it is with promises:
```php
$members = [...];
$addRole = function () use (&$addRole, &$members) {
    if ($member = array_shift($members) !== null) {
        return $member->addRole('role_id')->done($addRole);
    }

    return \React\Promise\resolve();
};
```
