### ISSUE TITLE
Embed null values

### ISSUE THREAD

**Issue by JaxkDev** [discord-php/DiscordPHP#492]
**Environment**
- PHP Version:
    - 7.4.12
- DiscordPHP Version:
    - master#6dec6e2

**Describe the bug**
When sending any embed with or without content you receive a update event for that same message  ≈ 0.017s later.
On the update for my own embed sent I receive a valid old message and new up to date new message with all fields expected to be filled, filled.
However when a different bot sends an embed to a server my bot is in it receives the create event, all good valid data (https://pastebin.com/e1VexjP2) BUT, when the update is called again ≈ 0.017s later no old message (null passed not a message obj) is passed to my event handler causing an error by itself and the new message is basically empty excluding its ID/Channel ID & embed content (https://pastebin.com/B2SCGC8c)

Raw event dump (https://pastebin.com/EjdMH8Mg)

**To Reproduce**
1. Find a bot that sends embeds, I was using Altdentifier that was sending a log embed to notify me that a channel was created/deleted, unsure if its reproduceable with other external bots.
2. Listen to message update event, dump new message and old message(if present)

**Expected behavior**
The message update event to pass both an old message and new message with at least the author present, the only reason I came across this was checking if the message came from a bot (simple author check failed, didn't know the author could be null...)

**Additional context**
Discussed in discord dont think anyone knows the exact cause so opened a issue for long term discussion/investigation.
Not a big problem for developers just change 3rd param type to null|Message on message update event, and check the new message has a valid author etc before using.

My bot has all intents enabled and has access to all channels/roles/members in that server (Administrator)

**Comment by davidcole1340** [comment]
I'll have a look this weekend

**Comment by davidcole1340** [comment]
The old message will be null because messages are not stored by the library by default, to enable it you can set `storeMessages` to `true` in the options, see here: http://discord-php.github.io/DiscordPHP/#basics

I'm not sure why a `MESSAGE_UPDATE` is sent, it seems redundant howewver.

**Comment by JaxkDev** [comment]
? It’s not the old message
Check the Pastebin for the issue data

**Comment by davidcole1340** [comment]
Yeah, what would be happening is that a `MESSAGE_CREATE` goes out with all the information minus the embed, and then `MESSAGE_UPDATE` comes in with only the `id`, `channel_id` and the `embed` fields. Since the messages aren't cached (`storeMessages` is not set) we don't have the original message from the `MESSAGE_CREATE` so merge with the embed received from the `MESSAGE_UPDATE`. This automatically happens if `storeMessages` is set.

**Comment by JaxkDev** [comment]
But as shown the embed is present on the MESSAGE_CREATE….

**Comment by davidcole1340** [comment]
I don't see what the problem is then? The `MESSAGE_UPDATE` is empty because the `MESSAGE_CREATE` isn't being cached (storeMessages is not set) and Discord only sends `id`, `channel_id`, `guild_id` and `embeds`:

These are the raw events from Discord:
![Screenshot from 2021-03-02 10-17-59](https://user-images.githubusercontent.com/991872/109560770-26dc6200-7b41-11eb-9e4e-79586fd18d91.png)

**Comment by JaxkDev** [comment]
Yes sorry drifted off, so originally it was because of the undocumented behaviour of a near null filled message on update (might be worth documenting that) and that it was a pointless event but that's discord 🤷 being discord.
