### ISSUE TITLE
Private channels not stored correctly

### ISSUE THREAD

**Issue by rederrik** [discord-php/DiscordPHP#493]
**Environment**
- PHP Version:
    - 7.4.5
- DiscordPHP Version:
    - dace512

**Describe the bug**
Title, I can't seem to get private channels by their ID using `Discord::getChannel`. Additionally, breakpoints set to every instance of `private_channels->push` never fire.
I know I can get private channels by other means, but I need this method for generic delayed events.

**To Reproduce**
```php
$discord->registerCommand(
    'pmtest',
    function (Message $message) use ($discord) {
        $chId = $message->channel_id;
        if ($channel = $discord->getChannel($chId)) {
            $channel->sendMessage('direct');
        } else {
            $message->reply('cant get private channel');
        }
    }
);
```
Then call this command in private channel with the bot - you should receive the 'cant get private channel' reply since `private_channels` repo is empty. `pmChannels` option value doesn't matter.

**Expected behavior**
Get 'direct' message  after firing this command in a private channel with the bot.

**Comment by davidcole1340** [comment]
Discord doesn't provide any way to retrieve existing private message channels, so they have to be "created" (actually returns the same channel every time) after every restart of the bot. When you call `$user->getPrivateChannel()` the channel will be cached so that it doesn't have to be "created" again. Is this what you were meaning?

**Comment by rederrik** [comment]
I mean, when the bots receives a command as a private message the channel is already being "created", isn't it? In my example, the `reply` to that channel works, but getting that channel from discord client doesn't.

**Comment by davidcole1340** [comment]
I just added a change on the `develop` branch, private channels will now be created if they don't exist. That's basically all we can do, we aren't able to get a list of private channel IDs from Discord, we have to wait until a user messages the bot.

**Comment by rederrik** [comment]
I'm confused with that change honestly, as my example still fails to get the channel from the client.

I tried this instead and it seem to work: 
```php
if(($channel = $message->channel) && ($channel->type === Channel::TYPE_DM)) {
    $this->discord->private_channels->push($channel);
}
```

Then I thought, "why do this in `MessageCreate` event?". So I reverted that change, went to `ChannelCreate` and changed
```php
if (isset($data->attributes['recipients'])) {
```
to
```php
if ($channel->type === Channel::TYPE_DM) {
```
And it worked too!

But why is `ChannelCreate` handler being run on every message?

**Comment by davidcole1340** [comment]
`CHANNEL_CREATE` will fire on each message because when a PM is sent, the channel is effectively 'created' again - see https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Parts/User/User.php#L70-L86 - which causes a `CHANNEL_CREATE` event.

I'm changing the `CHANNEL_CREATE` event handler to check the `is_private` attribute rather than the `recipients` attribute. Not sure why it was like that in the first place.

**Comment by putnam** [comment]
I think this may be broken again. I can PM my bot and the message handler fires and that message can be replied to just fine. But if I call getChannel with the channel ID used for this PM thread (for example, in an event handler for a react emoji) the result is null. I checked the private_channels array and it's empty.

Example. Some debug cruft in here from me trying to figure out what's going on. The goal would be for this function to work in both public and private channels, to act on reactions in some way like if there are 3 or more X's or something.

(If this handler is called by a reaction in a PM, the bot will crash since getChannel returns null.)

```php
  $discord->on(Event::MESSAGE_REACTION_ADD, function(MessageReaction $reaction, Discord $discord) {
    global $galleryMessages;
    l('Got reaction '.$reaction->emoji->name.' (id: '.$reaction->emoji->id.') to message ID '.$reaction->message_id);

    if (!isset($galleryMessages[$reaction->message_id])) return;

    l('Got react emoji to gallery message ('.$reaction->emoji->name.')');

    // Note that channel_id can represent a PM thread or a channel on some guild.
    l('Fetching channel ID '.$reaction->channel_id);
    l('Private channels:'.print_r($discord->private_channels, true));
    foreach ($discord->private_channels as $p) {
      l('Channel '.$p->channel_id);
    }
    $channel = $discord->getChannel($reaction->channel_id);
    $channel->messages->fetch($reaction->message_id, true)->done(function (Message $msg) {
      foreach ($msg->reactions as $r) {
        // Note: these are Reaction objects, not MessageReaction
        l('Reaction: '.$r->emoji->name.' Count: '.$r->count);
      }
    });

  });
```

**Comment by putnam** [comment]
I can see that the event handler for MessageCreate is supposed to be making a private channel when a new PM is received, but this code path is never hit today:

https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/WebSockets/Events/MessageCreate.php#L33

$messagePart->channel is not null when I send the (freshly inited) bot a new PM. So the private channel is not created internally or pushed into the private_channels array.

**Comment by putnam** [comment]
Some other thoughts because I can't find much in the docs:

1. If the bot restarts, some state may be carried over when it reopens. I am storing some existing conversation state with the bot by storing the channel id and message id, and then I can recover the state when the bot restarts. But when it comes to DMs there is no way with this library to get a handle on the DM channel again using a channel ID as far as I can tell. The official Discord API's /channels/ endpoints does this. But this library requires me to already have a guild object to fetch a channel by ID, and of course PM channels are not part of a guild. I have seen there may be a way to hack around this to recover this channel by using $user->getPrivateChannel (so I'd need to store the user id in the state too), but that brings me to my next thought..

2. What happens with group chats? They aren't mentioned anywhere in the docs. Aren't these going to be channels with multiple users? How would you recover these after a bot restart?

To me, the simple solution to everything is to just allow fetching a DM channel by ID from the client object itself. The `getChannel` method could already do this but right now is only assisting in juggling items from cache.

**Comment by SQKo** [comment]
> The problem is when you want to grab the channel outside of an event handler. You may know the channel ID because you carried state over from a previous running instance. But you still cannot retrieve it with this library, even though it’s possible with the official API channels endpoint.

already added in #825 use version `dev-master` deeb3c0

**Comment by putnam** [comment]
Oh cool! Thank you! I’ll check it out.
