### ISSUE TITLE
Random IP Ban

### ISSUE THREAD

**Issue by eqMFqfFd** [discord-php/DiscordPHP#501]
**Environment**
- PHP Version: 8.0.0
- DiscordPHP Version: d5a122d

**Describe the bug**

It has come to my attention that Discord is banning my IP randomly. When this happens, all my bots are disconnected and I can't log in.

I am aware of my recriminated "excessive" use, however I have 9/10 very lightweight bots running on a dedicated server, so I ask not to underestimate my issues.

I am partnered with a large community, in which a bot resides with which I am having issue #498. Independently, I have 9 other bots that are hosted on the same account.

Surprisingly, since I partnered with the 100,000-member community, and my message rate rises to 10,000+ messages per minute, I am IP banned. By this it follows that I must lower the limit message, and that should solve the problem, but? I want to find out why this happens, as it is just abnormal, and very limiting since I need large bots.

**Additional context**
This could be closely linked to #498, but I still want to dedicate its own issue to it.

**Comment by kenygamer** [comment]
When there is an IP ban, this happens:
![](https://i.ibb.co/M1hpCgr/0-A5578-D3-6-A19-474-F-B6-D4-FF0-DB5-CACE60.jpg)

**Comment by kenygamer** [comment]
```
{
  object(stdClass)#60919 (2) {
  ["code"]=>
  int(0)
  ["message"]=>
  string(212) "You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward."
}
```

**Comment by kenygamer** [comment]
@davidcole1340

**Comment by davidcole1340** [comment]
Fixed the `Undefined property` problem but you need to ask Discord for more information on what you are doing to get IP banned, no one else has had this issue.

**Comment by kenygamer** [comment]
@davidcole1340 I suppose that is because I am working with this program on a large-scale. My bot is on a server with 100,000 members, and loads of commands executing per minute. 

Lowering the requests per minute manually in the `HttpClient.php` has worked to cut down the error rate.

**Comment by key2peace** [comment]
https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit-aka-cloudflare-bans

**Comment by kenygamer** [comment]
> https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit-aka-cloudflare-bans

So, shouldn't this library have proper field sanitation to prevent this?

**Comment by kenygamer** [comment]
@key2peace So, shouldn't this library have proper field sanitization to prevent this?

**Comment by key2peace** [comment]
why do you require a library to protect you from your lack of care to think about what you send yourself? and if you really want it, perhaps add it yourself in a fork and send a pr?

**Comment by kenygamer** [comment]
@key2peace
> why do you require a library to protect you from your lack of care to think about what you send yourself? 

That's a very captious question. Notice that I have found code snippets that do actually sanitize fields: [Embed.php#L214](https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Parts/Embed/Embed.php#L214), [Embed.php#L174](https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Parts/Embed/Embed.php#L174), [Embed.php#L194](https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Parts/Embed/Embed.php#L194)

But I couldn't find the same here: [Footer.php#L28](https://github.com/discordphp/DiscordPHP/blob/master/src/Discord/Parts/Embed/Footer.php#L28), [Image.php#L29](https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Parts/Embed/Image.php#L29), [Video.php#L28](https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Parts/Embed/Video.php#L28)

There is a problem in your mindset, which is to think because something works doesn't mean that it cannot be improved.

> and if you really want it, perhaps add it yourself in a fork and send a pr?

So if you recognize that there is room for improvement. At the moment I cannot contribute code, but as a user of this library it is my job to report inconsistencies.
