### ISSUE TITLE
Unable to find roles from message author

### ISSUE THREAD

**Issue by AmaliaKalio** [discord-php/DiscordPHP#510]
**Environment**
- PHP Version:
    - 7.4.16
- DiscordPHP Version:
    - 5.1.2

**Describe the bug**
I have a requirement to lookup roles from a user posting a message, but this is not being returned either via print_r($message) or adding a function to the user class to return ($this->attributes).

message->author returns:
```
[author] => Discord\Parts\User\User Object
        (
            [id] => [redacted userID]
            [username] => [redacted userName]
            [avatar] => [redacted avatarURL]
            [discriminator] => 0584
            [bot] =>
            [system] =>
            [mfa_enabled] =>
            [locale] =>
            [verified] =>
            [email] =>
            [flags] =>
            [premium_type] =>
            [public_flags] => 256
        )
```

$this->attributes returns:
```
[username] => [redacted userName]
[public_flags] => 256
[id] => [redacted userID]
[discriminator] => 0584
[avatar] => [redacted avatarGUUID]
```

**To Reproduce**
```php
$discord->on('message', function ($message) {
    print_r($message);
});
```

**Expected behavior**
$message->author should contain an array named 'roles' containing roles assigned to the message author.

**Screenshots**
N/A

**Additional context**
I initially found mention of this on issue https://github.com/discord-php/DiscordPHP/issues/222 , and tested against a public channel to no avail.

**Comment by davidcole1340** [comment]
A `User` object represents a Discord user, which does not belong to a guild therefore does not have any roles, while a `Member` object represents a relationship between a user and a guild and will contain roles. Since `$message->author` is returning a `User` object you probably don't have the required intents enabled to receive guild members. See [here](https://discord.com/developers/docs/topics/gateway#privileged-intents) for how to enable them and the implications of doing so.

After enabling the intents, `$message->author` should return an instance of `Discord\Parts\User\Member` which has a `roles` property.

**Comment by AmaliaKalio** [comment]
That did it. Thanks!
