### ISSUE TITLE
Bot waits 60 seconds before triggering the "ready" event

### ISSUE THREAD

**Issue by paullaffitte** [discord-php/DiscordPHP#539]
**Environment**
- PHP Version:
    - 7.4.19
- DiscordPHP Version:
    - v6.0.1

**Describe the bug**
When I start my bot, it takes about 1 minute to trigger the `ready` event. It seems like there is an explicit statement in the source cade asking to wait 60 seconds if 1 guild is marked as `unavailable`. I don't understand why I would have to wait 1 full minute? For production it's arguably acceptable, but for development it's just not possible to wait 60 seconds after each code change.

**To Reproduce**
```php
$this->discord = new Discord([
    'token' => config('discord.bot_token'),
    'intents' => 52224,
]);

echo 'start\n';
$this->discord->on('ready', function (Discord $discord) {
    echo 'ready\n';
});
```

**Expected behavior**
I would like to get the ready event as soon as the bot is ready, not after an arbitrary 60 seconds.

**Comment by davidcole1340** [comment]
With your intents `52224`, you have enabled the intents `GUILD_MESSAGE_REACTIONS`, `GUILD_MESSAGE_TYPING` and `DIRECT_MESSAGE_TYPING`, the library also requires the `GUILDS` intent at a minimum to operate, so when you add that intent it should work. Setting `intents` to `19457` should work, this will enable `GUILDS` and the intents you have set above.

I think you are also doing your intents incorrectly as there is no intent at `(1 << 15)` which you have set. Intents are bitflags so not simple addition.

I will add the `GUILDS` intent as always on since the library depends on it.

**Comment by paullaffitte** [comment]
Thanks, I will try this during this week. However I'm well aware that intents are bitflags and I actually generated them on the discord developer website, I obviously don't want to calculate bitshifts by hand.

![image](https://user-images.githubusercontent.com/23403270/119473917-ed844e80-bd4b-11eb-9fe1-6bfc8dd53bd2.png)

**Comment by davidcole1340** [comment]
That's for permissions for roles, intents are different: https://discord.com/developers/docs/topics/gateway#gateway-intents

There are some intent calculators in the community resources section of the Discord documentation
