### ISSUE TITLE
sendMessage never gets triggered when $channel->find returns true

### ISSUE THREAD

**Issue by chrispelzer** [discord-php/DiscordPHP#750]
**Environment**
- PHP Version:
    - 8.1.3
- DiscordPHP Version:
    - 7.0.4

**Describe the bug**
I just updated to 7.0.4 from 7.0.3 and noticed that my sendMessage wasn't working. The function `$channels->find(function($channel){` returns true when it finds the correct channel, but it will just hang never triggering and going into the `sendMessage()` chained function.

**To Reproduce**
```php
        $this->discord->on('ready', function ($discord) {
            $discord->guilds->freshen()->done(function (GuildRepository $guilds) {
                $guilds->first()->channels->freshen()->done(function(ChannelRepository $channels) {
                    $channels->find(function ($channel) {
                        return $channel->name === $this->channel;
                    })->sendMessage('Hi from the Bot!')->done(function ($message) {
                        $this->info('Message sent!');

                        $this->discord->close();
                    });
                });
            });
        });
```

**Expected behavior**
The same behavior as 7.0.3 where when `$channels->find` returns true it should be triggering the sendMessage

**Comment by SQKo** [comment]
There are no changes with Collection::find() funtion between those versions, double check if the channel name youre comparing is still valid

Also under 'ready' event, you should not freshen the guild repository, that event is emitted when all guids data is loaded so you can simply access `$discord->guilds`
Note that $discord->guilds->first() returns the oldest guild id by the time it is created, not by the time your bot joined, same for channel.

since guilds are cached on 'ready', you can use this to get a specific Guild object:
`$guild = $discord->guilds['guild id here'];`

**Comment by chrispelzer** [comment]
> Also under 'ready' event, you should not freshen the guild repository, that event is emitted when all guids data is loaded so you can simply access `$discord->guilds` Note that `$discord->guilds->first()` returns the oldest guild id ordered by the snowflake (by the time it is created), not by the time your bot joined, same for channel.
> 
> since guilds are cached on 'ready', you can use this to get a specific Guild object: `$guild = $discord->guilds['guild id here'];`

Thanks! It was the flow of my code and that freshen was causing the odd behavior. Now it's working the same.

The bot is only used on 1 server so that's why I was grabbing the first. I fixed that up as well.
