### ISSUE TITLE
How to Send Embedded Message as DM

### ISSUE THREAD

**Issue by m00nm00nm00n** [discord-php/DiscordPHP#816]
How can I send an embed as a DM?

When I try to set $message->author->sendMessage argument as $message or $builder, it does not work..

what do I pass in? Thank you!

    $builder = MessageBuilder::new()->addEmbed($embed);
    $builder->setReplyTo($message);
    $channel = $discord->getChannel($message->channel_id);
    $channel->sendMessage($builder);
				
    // $message->author->sendMessage($message);
    // $message->delete();

**Comment by SQKo** [comment]
Please stop spamming issues for your similar questions

You need to create the `$embed` first

**Comment by m00nm00nm00n** [comment]
> 

???? I'm not spamming, and I did create $embed first.. this snippet was part of the code

i'm curious again how i'm spamming.. I have included different ways I tried to get it to work

**Comment by SQKo** [comment]
> > 
> 
> ???? I'm not spamming, 
> 
> i'm curious again how i'm spamming.. I have included different ways I tried to get it to work

You previously have this (still open): https://github.com/discord-php/DiscordPHP/issues/808
Your issue is no much different than that one.

> and I did create $embed first.. this snippet was part of the code

Then we cannot tell why it does not work, you show no error message nor full codes to reproduce the issue.
Consult the [documentation](https://discord-php.github.io/DiscordPHP) or [wiki](https://github.com/discord-php/DiscordPHP/wiki)
