### ISSUE TITLE
Unable to get roles from member

### ISSUE THREAD

**Issue by Kendaluski** [discord-php/DiscordPHP#817]
As the tittle says, my bot si unable to get a member role even though it has admin permissions. Anyone can help?

**Comment by SQKo** [comment]
Show your codes please

**Comment by Kendaluski** [comment]
![image](https://user-images.githubusercontent.com/105867025/170645816-476e8990-2a5f-4daf-ab01-155e826d56dc.png)

That's it

**Comment by SQKo** [comment]
Please post code as text next time, not as screenshot

I cannot reproduce the issue, `$member` is probably not cached, there are 2 solutions:

- Use `$guild->members->fetch($id)->done(...)`
- Enabled `loadAllMembers` options (and `GUILD_MEMBERS` intent), or enable `GUILD_PRESENCES` intent.

**Comment by Kendaluski** [comment]
Thank you so much, imma try that When I reach home, I think the solution si the loadAllMembers bc When I use that to give the bot a role works, but When I try to give to someone else it doesn't

**Comment by valzargaming** [comment]
> Thank you so much, imma try that When I reach home, I think the solution si the loadAllMembers bc When I use that to give the bot a role works, but When I try to give to someone else it doesn't

This is exactly why it wasn't working from you, then. When your bot connects to the gateway and is populated with guilds/servers it doesn't automatically get all information about their members by default. That means you'd either have to ask Discord for the role during runtime and within a promise scope if it isn't already in the cache, or you'd have to request them when it initially connects to the gateway (Which is what loadAllMembers does).

If you're in a lot of servers or in a few servers with several thousands of members you might not want to use loadAllMembers. I doubt this is the case for you right now though, so that'd be the best place to start.

**Comment by Kendaluski** [comment]
I understand now, I thought that if the bot has the admin rights it would be able to read all members, now it worker, thank u guys!
