### ISSUE TITLE
Collection cache data (eg.Users) can be cached in Redis?

### ISSUE THREAD

**Issue by roferwoo** [discord-php/DiscordPHP#863]
hello.
i'm using DiscordPHP v7.0.9.  
Want to fix "Allowed memory size of 1073741824 bytes exhausted (tried to allocate 10145560 bytes)
in /path/to/vendor/team-reflex/discord-php/src/Discord/Discord.php(#572)"

how can i change the cache data to Redis OR somewhere? Can someone writed that? thanks~

**Comment by SQKo** [comment]
Cache pool storage was removed since v5.0.0, We do have a plan to rewrite it back in future version v8.0.0

Disabling `loadAllMembers`, `storeMessages`, `retrieveBans` should reduce memory usage. Additionally to let PHP use whole available system memory, disable the memory limit `ini_set('memory_limit', '-1');` If your system only has 1 GB RAM, you have just reached the system memory.

**Comment by SQKo** [comment]
An experimental branch [`cacheInterface`](https://github.com/discord-php/DiscordPHP/tree/cacheInterface#cacheinterface-experimental-branch) is now available for development and testing. If you are interested, give it a try (be warned that breaking changes and issues may happen during the development period).
