### ISSUE TITLE
Autocomplete broken if there is no subcommand

### ISSUE THREAD

**Issue by ellisonpatterson** [discord-php/DiscordPHP#896]
**Environment**
- PHP Version:
    - 8.1.0
- DiscordPHP Version:
    - 7.2.5

**Describe the bug**
Autocomplete no longer works with this version. It looks like the `InteractionCreate` event now only calls suggest if there is a subcommand.

Before:
https://github.com/discord-php/DiscordPHP/blob/c09a2e85479c1c1474dd6330f1390d66e631a91a/src/Discord/WebSockets/Events/InteractionCreate.php#L67-L71

and with the newest version:
https://github.com/discord-php/DiscordPHP/blob/2471895bd449695d48fce8098dcddfc0699b1a99/src/Discord/WebSockets/Events/InteractionCreate.php#L61-L73

I'm creating a command this way:
```
$command = new Command($this->discord, [
    'name' => 'streetview',
    'description' => 'Get a Street View photo',
    'default_permission' => true,
    'options' => [
        new Option($this->discord, [
            'name' => 'address',
            'description' => 'Address or name of the location',
            'required' => true,
            'type' => Option::STRING,
            'autocomplete' => true
        ])
    ]
]);
```

Thank you!

**Comment by SQKo** [comment]
Fixed in 7.2.6, but to be noted the behavior is deprecated since there can be multiple options having autocomplete. If you have a required option, you must provide the options in the `listenCommand()` like:
```php
listenCommand(['streetview', 'address'], ...)
```
Note: doing so will also mean the command only execute when the option is provided. If you don't intend to do this, please don't use the autoComplete callback argument instead manually suggest from the interaction event.
